"""empty message

Revision ID: 33793d6f484e
Revises: 
Create Date: 2019-08-17 11:48:39.604818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33793d6f484e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_title', sa.String(length=150), nullable=True),
    sa.Column('entry_text', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_entry_text'), 'entry', ['entry_text'], unique=False)
    op.create_index(op.f('ix_entry_entry_title'), 'entry', ['entry_title'], unique=False)
    op.create_index(op.f('ix_entry_id'), 'entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_entry_title'), table_name='entry')
    op.drop_index(op.f('ix_entry_entry_text'), table_name='entry')
    op.drop_table('entry')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
