"""empty message

Revision ID: cf9a951985ae
Revises: 33793d6f484e
Create Date: 2019-08-17 13:26:48.852059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9a951985ae'
down_revision = '33793d6f484e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_entry_timestamp'), 'entry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_timestamp'), table_name='entry')
    op.drop_column('entry', 'timestamp')
    # ### end Alembic commands ###
